### ISSUE TITLE
Can we put constraints on the search space?

### ISSUE THREAD

**Issue by rzc331** [b-shields/edbo#13]
Hello, I can see in the examples that the chemical space is built in a hypercubic way. However, in my case I cannot reach all the points in this hypercube, instead I will need to put some constraints (e.g. the summation of coords value on all the axis is less than 1). 

Just wondering if we are allowed to do that using edbo, thanks!

**Comment by b-shields** [comment]
Sorry for the late response. You can constrain the search space. However, you will need to do it by explicitly selecting the points. This is because edbo is designed to optimize over an arbitrary search space passed as a pandas DataFrame. edbo will optimize over whatever you pass as the domain. https://b-shields.github.io/edbo/bro.html

**Comment by fnthibaud** [comment]
How does one go about updating the search space (in BO_express) after having selected the points one wants to include in it?
I have tried to update the objective like this: **bo.obj = objective(domain='new domain dataframe')** but am not sure whether this is the correct way.
